sudo: required
dist: trusty

language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential unzip
  - sudo apt-get build-dep -y gcc
  - pip install --user --upgrade awscli

install: true

script:
  - travis_wait 60 ./build.sh

after_success:
  - git fetch --tags --unshallow
  - PRODUCT_VERSION=v3 ./publish.sh buildroot/output/images/*
  - GITHUB_TOKEN=96fca5da87a01dfed440a40d3100ebfdc93ca807 SLACK_CHANNEL=github ./comment.sh

env:
  global:
    # Secure keys below are encrypted with travis encrypt gem
    # Example encryption: travis encrypt AWS_SECRET_ACCESS_KEY=foo
    # See https://docs.travis-ci.com/user/encryption-keys/
    # AWS_ACCESS_KEY_ID
    - secure: Ls9hEi04qvyDOEBbmDeNCjP7yfrQdke0EMFB8289xZPDrYNnysJmKzyh4Pt9PUyT7Y9pzrI1HKSziisshfQZWhhvG6K1fnM5glChoesK2pg4zeoz44gCsU/zGJqBNBH8z6VQgmAzeHvBPvOO9UJMy7ywD2Wz9+nQsYbWLgVE/63YuzEFsHI3jqLz5EyM4umpq2i6joQcD3Pdlvgs8KZj56lQ2IxrkTf1QMlwFN2/xmKa0eQctonCP7MwVyVCZEILUgpk7e0glfn86A+53fej/S8UhmCH6XHwUw9FQrmtEl4pwPmU1bna1pncWIorGChhcPorWD0ePfOCT4AKIrQAveaiSN/tnCzcmccVnGpe8WWXoRwFQ6B8110PbSwZlB9H5UUmZcpwmvIXnPyedbGVSXT2p2ubsjGBWbtnFj/uAms4izGAmOLUrvOx+rCb4ol2rP4WEnW22U927y6sotSAuj1BOkt4/x4nP6CZQNDXIOS4+kLRDjtNUrMFENhxbsdXbQ5ANZO5ssDPwI3hqNYamQWYKyasXgueLMBQdfaQ32nxBMQmN8dbvThsT/klQmsp5YoihndK6SGuF2IEIuWZG0cWACGnjHzrcv4dfBO2V5/7aoVhmSMKTUAvxkZsITYZuorUe+2HwQl6n59+0A2FhQdRLDMAXrOK7AN2faoJFhw=
    # AWS_SECRET_ACCESS_KEY
    - secure: vNHhGAZoaGmTiZ/Bjf0pqx4w9T37sDJNUOp6C5EXCapXAsYx+4G8v3xNlWBHWrPAs5q4XHJgbcNH7k1tRAI3nwd0RCv14SBNsVv5eouzpPd+o2ploDGCW++p/CL1kjQJBOqmz9sYCwxqra9LG7MCA/MzTG3eNa4/3lCf2tut7yhtxHbhIrVBaFgiHPYoZ1Pe6DPTQjjp32Xf2UHElHfa3oDQ/pw45hKWdwBx+fQjfLl1fVbHE3AhuXd7Q51tmL3qPNVox4/oLkmwpggzF0LoDQDZbZmOFSzcIiv/cpnqkaP9iy3TVQelrZivN9EXiyZsyhcrXll2pll/hvbg+cPVxBnC+p+yrPyZ4CaNwgID3c8ZRiPjJoyo+z4wxse3AaMv2AGsHVNGavYm61nFcJsRc0FQUfvkksdDu3LdfQbxkAKK7vgM7k4jWlcHe8wmQOXf/EPl5Hd2RNwHDfSEfR8YGPBDqsrdDFRO1fi/+kwpkLTfgN7WqbBBHCax54gQ1GZAEJC3nPqqnajKU/oduA4lXB2VJXlFl/NMeoX/z508Kc9wxaATCUFhGB68H2kKx8WT1ZMuBo9Eu7nXYSXg9jA+kCcb7GW3QgWk9h1Klcf6v5vw59UCFCEGfnPYinnWp6LMPHIY8q7ChpfEYq6rDma7o4bYExUHGo9Qip/qeEypetI=
    # GITHUB_TOKEN
    - secure: "LARO4dREORiPx00jLGGamNvW9so8NZvdSGJgPiXbiODVQz0KaY+AVrzsybO7BFpZg6NAE5wLUFBUyAAZreC2ffY+cg/ZvsmJrYR3t3Y64E4CMFH40VH0oO76M0uOFU/sgX7J7zBCZK9WXtqZMEwqcblAp1BYFzgZJbjfqU3s4Y27xKLG1BLxED1uZ/U2StHqkC2RFSiUi507rdkkKtytvYMTHxeQSM4tsejzqlyDDHc/OaImjDR1tHqRH0zLic5dCSnrJgFUAgzkMuAI+i8Zd+an5yYsFgzChINhkv/XYb5jL+8bRkDzkHCKxJebj+Ox5dCejqXU+y1C7dwCF+0z5SZN8kEXEeDnjCZEHcvZnHiVhxCDOmuVUtfaj83nkt/fV3tPY/aND2WO7pijq6R1WIDOUFNZzOLFTdZDEOeFYPiAnK2MijHksY3BnaK//3MGp+cIaJ+QTY+3TsNB1h3JGVI8ASqA1d6zhddHkGYRQoXRUlQt3plwl1TZx0RIAGn5iokFjdXLe0b+RYScE/dhdG9M3y2qCtKOYr79OR7YM6mnQEFNOt33EddC+qnlOq1f0kAEw41nswcbmMxzPpJQ3FeooVj2j10B10JKVE5V4LfPHXIhOJE5Pv9hXiUPuNtr+W+gkzI678fUvcmis6J0Zxo349EJ6IKM6VnMPzRkkKo="
    # SLACK_TOKEN
    - secure: "g0KII9TK5MhOS3j9h68jzQZk1bn6mVIaSMPrtB9aA7jrEMALm6biP+pYL2CgWyzGtFbsFVIG81fuyMpYjMR3ImFI/sGh+w0650HMaD97TEWYVc/gVtqjZsDbzGYtmG9tmxahJxl/LjAsO2xmddVYKlpyVzCGtAECe0IWX7LxYODIr01NQgmh6X+DClb1S6P1S6jgO4tjsnatstYo3us4jGHLqSDz9n9pH70YzZn8EB2cDQkLA5visc/w3mAMqmA3a3RWoBMNd3M63zEdlHWtiEaPY9JYDGASP1gp4rXAwKk5RTnNw6BBhVqqInfs1gFpXVve5zNus/YUZ342NuCyy2+pSSmJyWmA26pKE+PtHOoMuUwCqCrC/OdoLX7p7PTO++4XIr2vYV7KPlFELfzvlnCjXqlq8+AaiSb6z4FGijuHXRWNVvnasTcP3MDJn5OtjtBBNTiYm9fYj+z6PNVf9DwZbukiHN3GKNFEBGA1ACMvkD12BjDfrHsgLqHPUd9oRhU1qNGQVZozmVeKRczsP2lhwQp1GdrLhaz1ABeT0IjYqm+87LuE5eR0oQ/5ETOCDHdlfd4Vf6oz68lvkBbb2Yof55eJrSPUIzmLqCucEC1TI9WZui7isyRkhH9K5XCMQS0FKx6AvATOP4aG6zy8N5jAUYupR+NsCbDJUsQRc54="
