sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential unzip
  - sudo apt-get build-dep -y gcc

install: true

script: 
  - travis_wait 60 ./build.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./upload_artifacts.sh

