sudo: required
dist: trusty

language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential unzip
  - sudo apt-get build-dep -y gcc
  - pip install --user --upgrade awscli

install: true

script:
  - travis_wait 60 ./build.sh

after_success:
  - git fetch --tags --unshallow
  - test $TRAVIS_PULL_REQUEST != "false" && export BUCKET=swiftnav-artifacts-pull-requests && export ANONYMOUS=true || true
  - ./publish.sh v3 images/* || true
